version: "3.3"
services:
  darby-app:
    image: registry.pyn.ru/darby:latest
    ports:
      - 8082:8082
    volumes:
      - ./etc/application-prod.yml:/etc/myapp/application-prod.yml
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
