version: "3.3"
services:
  darby-app:
    image: registry.pyn.ru/darby:latest
    ports:
      - 8082:8082
    volumes:
      - ./src/etc/application-prod.yml:/etc/myapp/application-prod.yml
    restart: always
